name: flutter_crypto_wallet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.3
  dio: ^4.0.6
  flutter_screenutil: ^5.5.3+2
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  modal_bottom_sheet: ^2.0.1
  freezed_annotation:
  tuple: ^2.0.0
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  clipboard: ^0.1.3
  another_flushbar: 1.10.28
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  cupertino_icons: ^1.0.4
  web3dart: ^2.3.5
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.0.2
  cached_network_image: ^3.2.0
  persistent_bottom_nav_bar_v2: ^4.2.2
  shimmer: ^2.0.0
  injectable: ^1.5.3
  logger: ^1.1.0
  jiffy: ^5.0.0
  fl_chart: ^0.51.0
  sliver_tools: ^0.2.5
  json_annotation: ^4.5.0
  flutter_animated_dialog: ^2.0.1
  local_auth: ^2.0.2
  flutter_spinkit: ^5.1.0
  mobile_scanner: ^1.1.2
  qr_flutter: ^4.0.0
  share_plus: ^4.0.7

  custom_nested_scroll_view:
    git:
      url: https://github.com/idootop/custom_nested_scroll_view.git
      ref: eacb283d2f1b28e4fea2d262d3b12fd39837d02e
  custom_refresh_indicator: 1.1.1
  connectivity_plus: ^2.3.3




dev_dependencies:
  freezed: ^1.1.1
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  hive_generator: ^1.1.2
  injectable_generator: ^1.5.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800


flutter_intl:
  enabled: true
