name: flutter_ntf_marketplace
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.3
  provider: ^6.0.2
  dio: ^4.0.4
  flutter_screenutil: ^5.3.1
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  modal_bottom_sheet: ^2.0.0
  freezed_annotation:
  tuple: ^2.0.0
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  clipboard: ^0.1.3
  another_flushbar: ^1.10.28
  fluttertoast: ^8.0.8
  get: ^4.6.1


  cupertino_icons: ^1.0.4
  web3dart: ^2.3.5
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  freezed: ^1.1.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800

flutter_intl:
  enabled: true
